name: reusable workflow

on:
  # push:
  #   paths:
  #     - '.github/workflows/pipeline_automation.yml'
  workflow_dispatch:
    inputs: 
      service:
        required: true
        type: string
        default: java
      namespace:
        required: true
        type: string
        default: 17
      image_tag:
        required: true
        type: string
        default: adopt

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Deploy service
      #   uses: ./github/actions/deploy-service
      #   with:
      #     service: ${{ github.event.inputs.service }}
      #     namespace: ${{ github.event.inputs.namespace }}
      #     image_tag: ${{ github.event.inputs.image_tag }}

      - name: Notify deployment
        run: |
          echo "Deployment of ${{ github.event.inputs.service }} in namespace ${{ github.event.inputs.namespace }} with image tag ${{ github.event.inputs.image_tag }} completed."