mode: sequential
deployments:
  - name: my-service
    namespace: my-namespace
    image_tag: v1.0.0
  - name: my-service
    namespace: my-namespace
    image_tag: v1.2.0
  - name: my-service
    namespace: my-namespace
    image_tag: v1.3.0
