name: Automation pipeline

on:
  workflow_dispatch:
    inputs: 
      input:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/kishore3github/gradle-example/actions/workflows/build%20and%20push%20app.yaml/dispatches \
            -d '{
              "ref": "master",
              "inputs": {
                "language": "java",
                "version": "17",
                "distribution": "adopt"
              }
            }'
