name: Automation pipeline

on:
  workflow_dispatch:
    inputs: 
      language:
        required: true
        type: string
        default: java
      version:
        required: true
        type: string
        default: 17
      distribution:
        required: true
        type: string
        default: adopt

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          language: ${{ github.event.inputs.language }}
          version: ${{ github.event.inputs.version }}
          distribution: ${{ github.event.inputs.distribution }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/kishore3github/gradle-example/actions/workflows/build%20and%20push%20app.yaml/dispatches \
            -d "$(jq -n \
              --arg ref "master" \
              --arg language "$language" \
              --arg version "$version" \
              --arg distribution "$distribution" \
              '{
                ref: $ref,
                inputs: {
                  language: $language,
                  version: $version,
                  distribution: $distribution
                }
              }')"
      
