# .github/workflows/main.yaml
name: Service Deployment Controller

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode of operation'
        required: true
        default: 'sequential'
        type: choice
        options:
          - sequential
          - parallel

jobs:
  read-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo snap install yq

      - name: Read services
        id: read
        run: |
          echo "Reading services from services.yaml"
          matrix=$(yq -o=json '.deployments' services.yaml | jq -c)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "$matrix"

  deployments-parallel:
    needs: read-services
    if: ${{ github.event.inputs.mode == 'parallel' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.read-services.outputs.matrix) }}
    steps:
      - name: Call reusable deploy-service workflow
        uses: ./.github/workflows/deploy-service.yaml
        with:
          service: ${{ matrix.service.name }}
          namespace: ${{ matrix.service.namespace }}
          image_tag: ${{ matrix.service.image_tag }}

  deployments-sequential:
    needs: read-services
    if: ${{ github.event.inputs.mode == 'sequential' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy services sequentially
        env:
          MATRIX: ${{ needs.read-services.outputs.matrix }}
        run: |
          echo "Deploying services sequentially"
          echo "$MATRIX" | jq -c '.[]' | while read service; do
            name=$(echo $service | jq -r '.name')
            namespace=$(echo $service | jq -r '.namespace')
            image_tag=$(echo $service | jq -r '.image_tag')
            echo "Deploying $name in namespace $namespace with image tag $image_tag"
            gh workflow run deploy-service.yaml -f service="$name" -f namespace="$namespace" -f image_tag="$image_tag"
            echo "Deployment of $name in namespace $namespace with image tag $image_tag completed."
            sleep 10
          done
