name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'The name of the service to deploy'
        required: true
        type: string
      image:
        description: 'The image to use for deployment'
        required: true
        type: string
      namespace:
        description: 'The Kubernetes namespace to deploy to'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy service
        run: |
          echo "Deploying service ${{ inputs.service }} with image ${{ inputs.image }} to namespace ${{ inputs.namespace }}"
          # Here you would add your deployment logic, e.g., kubectl apply, helm upgrade, etc.
          # For demonstration, we just echo the values.
          echo "Deployment successful for ${{ inputs.service }}"