name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read versions.txt and create matrix
        id: set-matrix
        run: |
          matrix=$(awk -F= '{printf "{\service"\":\"%s\",\"version\":\"%s\"},", $1, $2}' versions.txt | sed 's/,$//')
          echo "matrix={\"include\":[${matrix}]}" >> $GITHUB_OUTPUT

  deploy:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy ${{ matrix.service }}
        run: |
          helm upgrade --install ${{ matrix.service }} ./charts/my-common-chart \
            --namespace ${{ matrix.service }} \
            --set image.tag=${{ matrix.version }} \
            -f environments/${{ matrix.service }}/values.yaml
